# -*- coding: utf-8 -*-
"""fineTunedUsingLora/QLora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TqULyuTfP9oKWheXLHU-F70TKmZiJoYW
"""

# =========================
# 1. INSTALL
# =========================
!pip install -U transformers datasets peft trl accelerate bitsandbytes

# =========================
# 2. IMPORTS
# =========================
import torch
from datasets import load_dataset

from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments
)

from peft import LoraConfig
from trl import SFTTrainer

# =========================
# 3. MODEL
# =========================
model_name = "NousResearch/Llama-2-7b-chat-hf"
new_model = "customer-support-qlora-bot"

# =========================
# 4. DATASET (BITEXT SUPPORT DATASET)
# =========================
dataset = load_dataset(
    "bitext/Bitext-customer-support-llm-chatbot-training-dataset",
    split="train"
)

# =========================
# 5. FORMAT DATASET (IMPORTANT FIX)
# =========================
def format_example(example):
    return {
        "text": f"""### Customer:
{example['instruction']}

### Agent:
{example['response']}"""
    }

dataset = dataset.map(format_example)
dataset = dataset.select(range(3000))

# =========================
# 6. QLoRA CONFIG
# =========================
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

# =========================
# 7. LOAD MODEL
# =========================
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

model.config.use_cache = False
model.config.pretraining_tp = 1

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

# =========================
# 8. LORA CONFIG
# =========================
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "v_proj"]
)

# =========================
# 9. TRAINING ARGS (SAFE VERSION)
# =========================
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=1,

    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,

    learning_rate=2e-4,
    weight_decay=0.001,

    fp16=False,
    bf16=False,

    optim="paged_adamw_32bit",
    lr_scheduler_type="cosine",
    warmup_ratio=0.03,

    logging_steps=25,
    save_steps=200,

    max_grad_norm=0.3,
    report_to="none",
    remove_unused_columns=False
)

# =========================
# 10. TRAINER (MODERN SAFE VERSION)
# =========================
trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    peft_config=peft_config,
    args=training_args
)

# =========================
# 11. TRAIN
# =========================
trainer.train()

# =========================
# 12. SAVE
# =========================
from google.colab import drive
drive.mount('/content/drive')

trainer.model.save_pretrained("/content/drive/MyDrive/support-bot")
tokenizer.save_pretrained("/content/drive/MyDrive/support-bot")

print("Saved to Google Drive")

!ls /content

"""# New Section"""